//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DST.ReportingService.Models.Camping {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class IndberetningsServiceDataDefinition {
        
        private IndberetningsServiceDataDefinitionTaellingsraekkeID taellingsraekkeIDField;
        
        private IndberetningsServiceDataDefinitionPeriodeStart periodeStartField;
        
        private IndberetningsServiceDataDefinitionPeriodeSlut periodeSlutField;
        
        private IndberetningsServiceDataDefinitionCVR cVRField;
        
        private IndberetningsServiceDataDefinitionEnhedsID enhedsIDField;
        
        private IndberetningsServiceDataDefinitionKontaktinformation kontaktinformationField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinition indberetningsdefinitionField;
        
        /// <remarks/>
        // CODEGEN-advarsel: Attributten 'fixed' understøttes kun for primitive typer. Attributten fixed='1156000' ignoreres.
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionTaellingsraekkeID TaellingsraekkeID {
            get {
                return this.taellingsraekkeIDField;
            }
            set {
                this.taellingsraekkeIDField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN-advarsel: Attributten 'fixed' understøttes kun for primitive typer. Attributten fixed='2019-08-01' ignoreres.
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionPeriodeStart PeriodeStart {
            get {
                return this.periodeStartField;
            }
            set {
                this.periodeStartField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN-advarsel: Attributten 'fixed' understøttes kun for primitive typer. Attributten fixed='2019-08-31' ignoreres.
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionPeriodeSlut PeriodeSlut {
            get {
                return this.periodeSlutField;
            }
            set {
                this.periodeSlutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionCVR CVR {
            get {
                return this.cVRField;
            }
            set {
                this.cVRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionEnhedsID EnhedsID {
            get {
                return this.enhedsIDField;
            }
            set {
                this.enhedsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionKontaktinformation Kontaktinformation {
            get {
                return this.kontaktinformationField;
            }
            set {
                this.kontaktinformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinition Indberetningsdefinition {
            get {
                return this.indberetningsdefinitionField;
            }
            set {
                this.indberetningsdefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionTaellingsraekkeID {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionTaellingsraekkeID() {
            this.beskrivelseField = "Statistik identifikationsnummer";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Statistik identifikationsnummer")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionPeriodeStart {
        
        private string beskrivelseField;
        
        private System.DateTime valueField;
        
        public IndberetningsServiceDataDefinitionPeriodeStart() {
            this.beskrivelseField = "Periode start";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Periode start")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionPeriodeSlut {
        
        private string beskrivelseField;
        
        private System.DateTime valueField;
        
        public IndberetningsServiceDataDefinitionPeriodeSlut() {
            this.beskrivelseField = "Periode slut";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Periode slut")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionCVR {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionCVR() {
            this.beskrivelseField = "CVR/CPR nummer";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("CVR/CPR nummer")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionEnhedsID {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionEnhedsID() {
            this.beskrivelseField = "Journal/SE/LOEBENR...";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Journal/SE/LOEBENR...")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionKontaktinformation {
        
        private string kontaktpersonNavnField;
        
        private string kontaktpersonTelefonField;
        
        private string kontaktpersonEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontaktpersonNavn {
            get {
                return this.kontaktpersonNavnField;
            }
            set {
                this.kontaktpersonNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontaktpersonTelefon {
            get {
                return this.kontaktpersonTelefonField;
            }
            set {
                this.kontaktpersonTelefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontaktpersonEmail {
            get {
                return this.kontaktpersonEmailField;
            }
            set {
                this.kontaktpersonEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinition {
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste ialtIkkeFasteField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal[] ikkeFasteLandeAntalField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste ialtFasteField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO ialtOField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal[] fasteLandeAntalField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh iAltEnhField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar aabnIAarField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar lukIAarField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon kontaktpers_telefonField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost kontaktpers_epostField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt antGaesterIaltField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK antGaesterDKField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn kontaktpers_navnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste IaltIkkeFaste {
            get {
                return this.ialtIkkeFasteField;
            }
            set {
                this.ialtIkkeFasteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IkkeFasteLandeAntal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal[] IkkeFasteLandeAntal {
            get {
                return this.ikkeFasteLandeAntalField;
            }
            set {
                this.ikkeFasteLandeAntalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste IaltFaste {
            get {
                return this.ialtFasteField;
            }
            set {
                this.ialtFasteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO IaltO {
            get {
                return this.ialtOField;
            }
            set {
                this.ialtOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FasteLandeAntal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal[] FasteLandeAntal {
            get {
                return this.fasteLandeAntalField;
            }
            set {
                this.fasteLandeAntalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh IAltEnh {
            get {
                return this.iAltEnhField;
            }
            set {
                this.iAltEnhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar AabnIAar {
            get {
                return this.aabnIAarField;
            }
            set {
                this.aabnIAarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar LukIAar {
            get {
                return this.lukIAarField;
            }
            set {
                this.lukIAarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon Kontaktpers_telefon {
            get {
                return this.kontaktpers_telefonField;
            }
            set {
                this.kontaktpers_telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost Kontaktpers_epost {
            get {
                return this.kontaktpers_epostField;
            }
            set {
                this.kontaktpers_epostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt AntGaesterIalt {
            get {
                return this.antGaesterIaltField;
            }
            set {
                this.antGaesterIaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK AntGaesterDK {
            get {
                return this.antGaesterDKField;
            }
            set {
                this.antGaesterDKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn kontaktpers_navn {
            get {
                return this.kontaktpers_navnField;
            }
            set {
                this.kontaktpers_navnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste() {
            this.beskrivelseField = "Ikke-fastliggende gæstenætter i alt";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Ikke-fastliggende gæstenætter i alt")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal {
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode iFLandekodeField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand iFOvernatningerFraLandField;
        
        private string beskrivelseField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal() {
            this.beskrivelseField = "Gruppe af landekoder - bruges til at fordele antal ikke-fastliggende gæstenætter " +
                "på specifikke lande ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode IFLandekode {
            get {
                return this.iFLandekodeField;
            }
            set {
                this.iFLandekodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand IFOvernatningerFraLand {
            get {
                return this.iFOvernatningerFraLandField;
            }
            set {
                this.iFOvernatningerFraLandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Gruppe af landekoder - bruges til at fordele antal ikke-fastliggende gæstenætter " +
            "på specifikke lande ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode() {
            this.beskrivelseField = "Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
                "staver, fx SWE for Sverige.";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
            "staver, fx SWE for Sverige.")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand() {
            this.beskrivelseField = "Antal ikke-fastliggende gæstenætter fra specificeret land ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal ikke-fastliggende gæstenætter fra specificeret land ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste() {
            this.beskrivelseField = "Fast udlejede standpladser i alt";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Fast udlejede standpladser i alt")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO() {
            this.beskrivelseField = "Fast udlejede standpladser i alt omregnet til antal gæstenætter";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Fast udlejede standpladser i alt omregnet til antal gæstenætter")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal {
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode landekodeField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand antalUdlejedeFasteFraLandField;
        
        private IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand antalOvernatningerFraLandField;
        
        private string beskrivelseField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal() {
            this.beskrivelseField = "Gruppe af landekoder - bruges til at fordele antal fastliggende gæstenætter på sp" +
                "ecifikke lande ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode Landekode {
            get {
                return this.landekodeField;
            }
            set {
                this.landekodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand AntalUdlejedeFasteFraLand {
            get {
                return this.antalUdlejedeFasteFraLandField;
            }
            set {
                this.antalUdlejedeFasteFraLandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand AntalOvernatningerFraLand {
            get {
                return this.antalOvernatningerFraLandField;
            }
            set {
                this.antalOvernatningerFraLandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Gruppe af landekoder - bruges til at fordele antal fastliggende gæstenætter på sp" +
            "ecifikke lande ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode() {
            this.beskrivelseField = "Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
                "staver, fx SWE for Sverige.";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
            "staver, fx SWE for Sverige.")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand() {
            this.beskrivelseField = "Antal fast udlejede pladser fra specificeret land";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal fast udlejede pladser fra specificeret land")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand() {
            this.beskrivelseField = "Antal gæstenætter på fast udlejede standpladser fra specificeret land ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal gæstenætter på fast udlejede standpladser fra specificeret land ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh() {
            this.beskrivelseField = "Kapacitet - Antal campingenheder";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kapacitet - Antal campingenheder")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar() {
            this.beskrivelseField = "Felt til angivelse af åbningsperiode - Åbner";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Felt til angivelse af åbningsperiode - Åbner")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar() {
            this.beskrivelseField = "Felt til angivelse af åbningsperiode - Lukker";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Felt til angivelse af åbningsperiode - Lukker")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon() {
            this.beskrivelseField = "Kontaktpersonens telefonnummer";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kontaktpersonens telefonnummer")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost() {
            this.beskrivelseField = "Kontaktpersonens e-mail";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kontaktpersonens e-mail")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt() {
            this.beskrivelseField = "Antal gæster i alt (udenlandske og danske lagt sammen)";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal gæster i alt (udenlandske og danske lagt sammen)")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK() {
            this.beskrivelseField = "Antal danske gæster i alt";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal danske gæster i alt")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public IndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn() {
            this.beskrivelseField = "Kontaktpersonens navn";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kontaktpersonens navn")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
