//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DST.ReportingService.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CampingIndberetningsServiceDataDefinition
    {
        
        private CampingIndberetningsServiceDataDefinitionTaellingsraekkeID taellingsraekkeIDField;
        
        private CampingIndberetningsServiceDataDefinitionPeriodeStart periodeStartField;
        
        private CampingIndberetningsServiceDataDefinitionPeriodeSlut periodeSlutField;
        
        private CampingIndberetningsServiceDataDefinitionCVR cVRField;
        
        private CampingIndberetningsServiceDataDefinitionEnhedsID enhedsIDField;
        
        private CampingIndberetningsServiceDataDefinitionKontaktinformation kontaktinformationField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinition indberetningsdefinitionField;
        
        /// <remarks/>
        // CODEGEN-advarsel: Attributten 'fixed' understøttes kun for primitive typer. Attributten fixed='1156000' ignoreres.
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionTaellingsraekkeID TaellingsraekkeID {
            get {
                return this.taellingsraekkeIDField;
            }
            set {
                this.taellingsraekkeIDField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN-advarsel: Attributten 'fixed' understøttes kun for primitive typer. Attributten fixed='2019-08-01' ignoreres.
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionPeriodeStart PeriodeStart {
            get {
                return this.periodeStartField;
            }
            set {
                this.periodeStartField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN-advarsel: Attributten 'fixed' understøttes kun for primitive typer. Attributten fixed='2019-08-31' ignoreres.
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionPeriodeSlut PeriodeSlut {
            get {
                return this.periodeSlutField;
            }
            set {
                this.periodeSlutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionCVR CVR {
            get {
                return this.cVRField;
            }
            set {
                this.cVRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionEnhedsID EnhedsID {
            get {
                return this.enhedsIDField;
            }
            set {
                this.enhedsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionKontaktinformation Kontaktinformation {
            get {
                return this.kontaktinformationField;
            }
            set {
                this.kontaktinformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinition Indberetningsdefinition {
            get {
                return this.indberetningsdefinitionField;
            }
            set {
                this.indberetningsdefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionTaellingsraekkeID
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionTaellingsraekkeID() {
            this.beskrivelseField = "Statistik identifikationsnummer";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Statistik identifikationsnummer")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionPeriodeStart
    {
        
        private string beskrivelseField;
        
        private System.DateTime valueField;
        
        public CampingIndberetningsServiceDataDefinitionPeriodeStart() {
            this.beskrivelseField = "Periode start";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Periode start")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionPeriodeSlut
    {
        
        private string beskrivelseField;
        
        private System.DateTime valueField;
        
        public CampingIndberetningsServiceDataDefinitionPeriodeSlut() {
            this.beskrivelseField = "Periode slut";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Periode slut")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionCVR
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionCVR() {
            this.beskrivelseField = "CVR/CPR nummer";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("CVR/CPR nummer")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionEnhedsID
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionEnhedsID() {
            this.beskrivelseField = "Journal/SE/LOEBENR...";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Journal/SE/LOEBENR...")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionKontaktinformation
    {
        
        private string kontaktpersonNavnField;
        
        private string kontaktpersonTelefonField;
        
        private string kontaktpersonEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontaktpersonNavn {
            get {
                return this.kontaktpersonNavnField;
            }
            set {
                this.kontaktpersonNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontaktpersonTelefon {
            get {
                return this.kontaktpersonTelefonField;
            }
            set {
                this.kontaktpersonTelefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontaktpersonEmail {
            get {
                return this.kontaktpersonEmailField;
            }
            set {
                this.kontaktpersonEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinition
    {
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste ialtIkkeFasteField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal[] ikkeFasteLandeAntalField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste ialtFasteField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO ialtOField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal[] fasteLandeAntalField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh iAltEnhField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar aabnIAarField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar lukIAarField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon kontaktpers_telefonField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost kontaktpers_epostField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt antGaesterIaltField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK antGaesterDKField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn kontaktpers_navnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste IaltIkkeFaste {
            get {
                return this.ialtIkkeFasteField;
            }
            set {
                this.ialtIkkeFasteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IkkeFasteLandeAntal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal[] IkkeFasteLandeAntal {
            get {
                return this.ikkeFasteLandeAntalField;
            }
            set {
                this.ikkeFasteLandeAntalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste IaltFaste {
            get {
                return this.ialtFasteField;
            }
            set {
                this.ialtFasteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO IaltO {
            get {
                return this.ialtOField;
            }
            set {
                this.ialtOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FasteLandeAntal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal[] FasteLandeAntal {
            get {
                return this.fasteLandeAntalField;
            }
            set {
                this.fasteLandeAntalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh IAltEnh {
            get {
                return this.iAltEnhField;
            }
            set {
                this.iAltEnhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar AabnIAar {
            get {
                return this.aabnIAarField;
            }
            set {
                this.aabnIAarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar LukIAar {
            get {
                return this.lukIAarField;
            }
            set {
                this.lukIAarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon Kontaktpers_telefon {
            get {
                return this.kontaktpers_telefonField;
            }
            set {
                this.kontaktpers_telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost Kontaktpers_epost {
            get {
                return this.kontaktpers_epostField;
            }
            set {
                this.kontaktpers_epostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt AntGaesterIalt {
            get {
                return this.antGaesterIaltField;
            }
            set {
                this.antGaesterIaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK AntGaesterDK {
            get {
                return this.antGaesterDKField;
            }
            set {
                this.antGaesterDKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn kontaktpers_navn {
            get {
                return this.kontaktpers_navnField;
            }
            set {
                this.kontaktpers_navnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltIkkeFaste() {
            this.beskrivelseField = "Ikke-fastliggende gæstenætter i alt";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Ikke-fastliggende gæstenætter i alt")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal
    {
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode iFLandekodeField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand iFOvernatningerFraLandField;
        
        private string beskrivelseField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntal() {
            this.beskrivelseField = "Gruppe af landekoder - bruges til at fordele antal ikke-fastliggende gæstenætter " +
                "på specifikke lande ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode IFLandekode {
            get {
                return this.iFLandekodeField;
            }
            set {
                this.iFLandekodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand IFOvernatningerFraLand {
            get {
                return this.iFOvernatningerFraLandField;
            }
            set {
                this.iFOvernatningerFraLandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Gruppe af landekoder - bruges til at fordele antal ikke-fastliggende gæstenætter " +
            "på specifikke lande ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFLandekode() {
            this.beskrivelseField = "Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
                "staver, fx SWE for Sverige.";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
            "staver, fx SWE for Sverige.")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIkkeFasteLandeAntalIFOvernatningerFraLand() {
            this.beskrivelseField = "Antal ikke-fastliggende gæstenætter fra specificeret land ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal ikke-fastliggende gæstenætter fra specificeret land ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltFaste() {
            this.beskrivelseField = "Fast udlejede standpladser i alt";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Fast udlejede standpladser i alt")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIaltO() {
            this.beskrivelseField = "Fast udlejede standpladser i alt omregnet til antal gæstenætter";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Fast udlejede standpladser i alt omregnet til antal gæstenætter")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal
    {
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode landekodeField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand antalUdlejedeFasteFraLandField;
        
        private CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand antalOvernatningerFraLandField;
        
        private string beskrivelseField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntal() {
            this.beskrivelseField = "Gruppe af landekoder - bruges til at fordele antal fastliggende gæstenætter på sp" +
                "ecifikke lande ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode Landekode {
            get {
                return this.landekodeField;
            }
            set {
                this.landekodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand AntalUdlejedeFasteFraLand {
            get {
                return this.antalUdlejedeFasteFraLandField;
            }
            set {
                this.antalUdlejedeFasteFraLandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand AntalOvernatningerFraLand {
            get {
                return this.antalOvernatningerFraLandField;
            }
            set {
                this.antalOvernatningerFraLandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Gruppe af landekoder - bruges til at fordele antal fastliggende gæstenætter på sp" +
            "ecifikke lande ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalLandekode() {
            this.beskrivelseField = "Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
                "staver, fx SWE for Sverige.";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Landekode - Angives jævnfør ISO 3166. Vi benytter den kode, som består af tre bog" +
            "staver, fx SWE for Sverige.")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalUdlejedeFasteFraLand() {
            this.beskrivelseField = "Antal fast udlejede pladser fra specificeret land";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal fast udlejede pladser fra specificeret land")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionFasteLandeAntalAntalOvernatningerFraLand() {
            this.beskrivelseField = "Antal gæstenætter på fast udlejede standpladser fra specificeret land ";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal gæstenætter på fast udlejede standpladser fra specificeret land ")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionIAltEnh() {
            this.beskrivelseField = "Kapacitet - Antal campingenheder";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kapacitet - Antal campingenheder")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAabnIAar() {
            this.beskrivelseField = "Felt til angivelse af åbningsperiode - Åbner";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Felt til angivelse af åbningsperiode - Åbner")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionLukIAar() {
            this.beskrivelseField = "Felt til angivelse af åbningsperiode - Lukker";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Felt til angivelse af åbningsperiode - Lukker")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon 
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_telefon() {
            this.beskrivelseField = "Kontaktpersonens telefonnummer";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kontaktpersonens telefonnummer")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost 
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_epost() {
            this.beskrivelseField = "Kontaktpersonens e-mail";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kontaktpersonens e-mail")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterIalt() {
            this.beskrivelseField = "Antal gæster i alt (udenlandske og danske lagt sammen)";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal gæster i alt (udenlandske og danske lagt sammen)")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionAntGaesterDK() {
            this.beskrivelseField = "Antal danske gæster i alt";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Antal danske gæster i alt")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn 
    {
        
        private string beskrivelseField;
        
        private string valueField;
        
        public CampingIndberetningsServiceDataDefinitionIndberetningsdefinitionKontaktpers_navn() {
            this.beskrivelseField = "Kontaktpersonens navn";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Kontaktpersonens navn")]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
